# Generated by Django 6.0.1 on 2026-02-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_lobby_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='host',
            field=models.IntegerField(null=True),
        ),
    ]
