# Generated by Django 6.0.1 on 2026-02-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_user_name_lobby_isactive_player_isplaying_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='hostLeft',
            field=models.BooleanField(default=False),
        ),
    ]
