# Generated by Django 6.0.1 on 2026-02-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_lobby_hostleft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='hostLeft',
        ),
    ]
