# Generated by Django 6.0.1 on 2026-03-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_lobby_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='time',
            field=models.IntegerField(default=30),
        ),
    ]
