# Generated by Django 6.0.1 on 2026-03-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_lobby_time'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lobby',
            constraint=models.CheckConstraint(condition=models.Q(('time__in', [30, 60, 90])), name='valid_lobby_time'),
        ),
        migrations.AddConstraint(
            model_name='lobby',
            constraint=models.CheckConstraint(condition=models.Q(('isActive', True), ('results', True), _negated=True), name='not_active_and_results_simultaneously'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(condition=models.Q(('score__gt', 0)), name='Score_must_be_gt_zero'),
        ),
    ]
