# Generated by Django 6.0.1 on 2026-03-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_lobby_valid_lobby_time_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='player',
            name='Score_must_be_gt_zero',
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='Score_must_be_gt_zero'),
        ),
    ]
